-- MarketGen -- SQLite schema. This is the path that actually runs locally and
-- in the test suite. It mirrors migrations/postgres/001_schema.sql, with these
-- deliberate differences:
--
--   * uuid    -> text (ids generated by the application)
--   * jsonb   -> text holding JSON (serialised by the application)
--   * timestamptz -> text holding ISO-8601 UTC
--   * SQLite has no row-level security, so the equivalent guarantee comes from
--     app/tenancy.py's guard plus mandatory tenant predicates in app/store.py.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS tenants (
    id          TEXT PRIMARY KEY,
    slug        TEXT NOT NULL UNIQUE,
    name        TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
    id           TEXT PRIMARY KEY,
    tenant_id    TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    key_hash     TEXT NOT NULL UNIQUE,
    actor_email  TEXT NOT NULL,
    role         TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'admin')),
    revoked_at   TEXT,
    created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS api_keys_tenant_idx ON api_keys (tenant_id);

CREATE TABLE IF NOT EXISTS clients (
    id          TEXT PRIMARY KEY,
    tenant_id   TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    UNIQUE (tenant_id, name)
);
CREATE INDEX IF NOT EXISTS clients_tenant_idx ON clients (tenant_id);

CREATE TABLE IF NOT EXISTS onboarding_sessions (
    id                    TEXT PRIMARY KEY,
    tenant_id             TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    client_id             TEXT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    status                TEXT NOT NULL DEFAULT 'in_progress'
                            CHECK (status IN ('in_progress', 'completed', 'abandoned')),
    current_step          INTEGER NOT NULL DEFAULT 1 CHECK (current_step BETWEEN 1 AND 7),
    answers               TEXT NOT NULL DEFAULT '{}',
    completed_steps       TEXT NOT NULL DEFAULT '[]',
    questionnaire_version TEXT NOT NULL,
    created_at            TEXT NOT NULL,
    updated_at            TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS onboarding_tenant_idx ON onboarding_sessions (tenant_id);
CREATE INDEX IF NOT EXISTS onboarding_tenant_client_idx ON onboarding_sessions (tenant_id, client_id);

CREATE TABLE IF NOT EXISTS campaign_briefs (
    id          TEXT PRIMARY KEY,
    tenant_id   TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    session_id  TEXT NOT NULL REFERENCES onboarding_sessions(id) ON DELETE CASCADE,
    provider    TEXT NOT NULL,
    brief       TEXT NOT NULL,
    created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS briefs_tenant_idx ON campaign_briefs (tenant_id);
CREATE INDEX IF NOT EXISTS briefs_tenant_session_idx ON campaign_briefs (tenant_id, session_id);

CREATE TABLE IF NOT EXISTS generated_posts (
    id             TEXT PRIMARY KEY,
    tenant_id      TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    brief_id       TEXT NOT NULL REFERENCES campaign_briefs(id) ON DELETE CASCADE,
    channel        TEXT NOT NULL,
    format         TEXT NOT NULL,
    headline       TEXT NOT NULL,
    body           TEXT NOT NULL,
    call_to_action TEXT NOT NULL,
    hashtags       TEXT NOT NULL DEFAULT '[]',
    image_prompt   TEXT,
    image_ref      TEXT,
    created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS posts_tenant_idx ON generated_posts (tenant_id);
CREATE INDEX IF NOT EXISTS posts_tenant_brief_idx ON generated_posts (tenant_id, brief_id);

CREATE TABLE IF NOT EXISTS publish_attempts (
    id          TEXT PRIMARY KEY,
    tenant_id   TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    post_id     TEXT NOT NULL REFERENCES generated_posts(id) ON DELETE CASCADE,
    adapter     TEXT NOT NULL,
    dry_run     INTEGER NOT NULL DEFAULT 1,
    status      TEXT NOT NULL CHECK (status IN ('dry_run', 'succeeded', 'failed', 'blocked')),
    detail      TEXT NOT NULL DEFAULT '{}',
    created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS attempts_tenant_idx ON publish_attempts (tenant_id);
